import './types.js';
import './ontologies/lincd-server.js';
//SHAPES FIRST
import './shapes/LincdServer.js';
import './shapes/LincdAPI.js';
import './shapes/quadstores/BackendAPIStore.js';
import './shapes/filestores/LocalFileStore.js';
import './shapes/LincdWebApp.js';
//THEN COMPONENTS
import './utils/accessUrl.js';
//# sourceMappingURL=index.js.map